// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbgukrjlbfhawferxgpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZ3VrcmpsYmZoYXdmZXJ4Z3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzQ5NzgsImV4cCI6MjA3MzAxMDk3OH0.w6QdU8XEtGdDzFtvIIWyqPkQb46QA7aCY33XV8pwDM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});